
data-source-configs:
  fir-datasource:
    type: com.zaxxer.hikari.HikariDataSource
    data-config:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/firchat_fir?useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        pool-name: HikariCP
        auto-commit: false
        connection-timeout: 5000
        max-lifetime: 600000
        maximum-pool-size: 50
        minimum-idle: 5

service:
  general:
    redis-config:
      # 配置模式: single, cluster, elasticcache:
      mode: single
      # Redis节点地址列表:
      nodes:
        - redis://127.0.0.1:6379
    lock-zookeeper-config:
      zookeeperAddr: 127.0.0.1:2181
      zkpTimeout: 10000
    db-config:
      redisKey: ${REDIS_KEY:}
      defaultDbName: ${DEFAULT_DB_NAME:}
      autoUpdateTableName: ${AUTO_UPDATE_TALBE_NAME:db_service_update}
      primaryKey: ${PRIMARY_KEY:id}
      versionKey: ${VERSION_KEY:version}
      tableNameTag: ${TABLE_NAME_TAG:__TABLE_NAME}
    data-source-type-suffix: type
    data-source-config-suffix: data-config
  micro-service:
    common:
      registry-address: zookeeper://192.168.7.101:2181
    simple-other-service:
      application-name: simple-other-service
      protocol-name: dubbo
      protocol-port: ${MICRO_SERVICE_PORT:30810}
      scan: org.dragonli.service.general.other.OtherService
      group: ${MICRO_SERVICE_GROUP:}
      http-port: ${MICRO_SERVICE_HTTP_PORT:7094}
      zookeeper-address: 127.0.0.1:2181
      zookeeper-timeout: 3000
      zookeeper-base-key: /service/datas/lock/base
      lock-timeout: 1000
    simple-netty-service:
      application-name: simple-netty-service
      protocol-name: dubbo
      protocol-port: ${MICRO_SERVICE_PORT:30809}
      scan: org.dragonli.service.general.interfaces.general.WebSocketService
      http-port: ${MICRO_SERVICE_HTTP_PORT:7096}
      group: ${MICRO_SERVICE_GROUP:}
      onlinePrefix: ${NETTY_ONLINE_ZOOKEEPER_PATH_PREFIX:/service/datas/websocket/online:}
      configsStr: ${NETTY_CONFIG_STR:127.0.0.1:8101;ws://websocket-dev-address:8101}
      redisonlineKey: /service/datas/websocket/online
      privatekey: ${CONFIG_PRIVATE_KEY:draonli@2019}
    simple-db-service:
      application-name: simple-db-service
      protocol-name: dubbo
      protocol-port: ${MICRO_SERVICE_PORT:30807}
      scan: org.dragonli.service.db.service.DbService
      http-port: ${MICRO_SERVICE_HTTP_PORT:7093}
      group: ${MICRO_SERVICE_GROUP:}
    dubbo-consumer-proxy-service:
      application-name: dubbo-consumer-proxy-service
      protocol-name: dubbo
      protocol-port: ${MICRO_SERVICE_PORT:30800}
      scan: org.dragonli.service.general.dubboconsumerservice.ConsumerService
      http-port: ${MICRO_SERVICE_HTTP_PORT:7090}
      netty-port: ${MICRO_SERVICE_NETTY_PORT:7089}
      telnet-port: ${MICRO_SERVICE_TELNET_PORT:50800}